// Disposable PostgreSQL regression test; no production connection or root
// dependency installation. Set PGLITE_MODULE_PATH to a PGlite module if needed.
// This task uses pinned @electric-sql/pglite@0.5.8 in the isolated output runtime.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {pathToFileURL} from 'node:url';

const runtime=new URL('../../outputs/season-reset-20261010/test-runtime/node_modules/@electric-sql/pglite/dist/index.js',import.meta.url);
const moduleUrl=process.env.PGLITE_MODULE_PATH?pathToFileURL(process.env.PGLITE_MODULE_PATH).href:runtime.href;
const {PGlite}=await import(moduleUrl);
const migration=fs.readFileSync(new URL('../supabase/migrations/20261010014732_fresh_beta_season_20261010.sql',import.meta.url),'utf8');
const backup=new URL('../../outputs/season-reset-20261010/previous-season-functions.sql',import.meta.url);
let previous;
if(fs.existsSync(backup)){
 // pg_get_functiondef does not include a delimiter between exported functions.
 previous=fs.readFileSync(backup,'utf8').replace(/\$function\$(?=\s*(?:CREATE OR REPLACE FUNCTION|$))/g,'$function$;');
}else{
 const extract=(file,name)=>{
  const sql=fs.readFileSync(new URL('../supabase/migrations/'+file,import.meta.url),'utf8');
  const start=sql.indexOf('create or replace function public.'+name+'(');assert(start>=0);
  const body=sql.indexOf('as $$',start),end=sql.indexOf('$$;',body+5);assert(end>body);
  return sql.slice(start,end+3);
 };
 previous=extract('20260916072036_perfect_classic_draft_rankings.sql','get_leaderboard')+'\n'+extract('20260916072053_beta_season_standings.sql','get_beta_season_status');
}
const db=await PGlite.create('memory://');
const rows=async(sql,params=[])=>(await db.query(sql,params)).rows;
const one=async(sql,params=[])=>(await rows(sql,params))[0];
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const users={a:id(1),b:id(2),c:id(3),old:id(4),newcomer:id(5),pending:id(6),period:id(7)};
let nextRun=1000;
const leaderboard=(mode='draft',period='all_time',limit=50)=>rows('select * from public.get_leaderboard($1,$2,$3)',[mode,period,limit]);
const status=async()=>((await one('select public.get_beta_season_status() as value')).value);
const viewer=async user=>{await db.query("select set_config('request.jwt.claim.sub',$1,true)",[user||'']);return status();};
async function profile(user,name){await db.query('insert into public.profiles(id,public_id,username,display_name) values($1,$2,$3,$3)',[user,id(Number(user.slice(-12))+10000),name]);}
async function result({user=users.a,mode='draft',rules='atu-classic-v14',runAt='now()',entryAt=runAt,points=1098,wins=82,losses=0,runUser=user,runMode=mode,runStatus='completed'}={}){
 const run=id(++nextRun);
 // Timestamp expressions are fixed test constants, never external input.
 await db.query(`insert into public.game_runs(id,user_id,mode,rules_version,status,created_at) values($1,$2,$3,$4,$5,${runAt})`,[run,runUser,runMode,rules,runStatus]);
 await db.query(`insert into public.leaderboard_entries(run_id,user_id,mode,points,wins,losses,team_ovr,rules_version,result_digest,created_at) values($1,$2,$3,$4,$5,$6,98,$7,$8,${entryAt})`,[run,user,mode,points,wins,losses,rules,run]);
 return run;
}
async function tableSnapshot(){return one(`select
 (select jsonb_agg(to_jsonb(t) order by id) from public.profiles t) as profiles,
 (select jsonb_agg(to_jsonb(t) order by id) from public.game_runs t) as runs,
 (select jsonb_agg(to_jsonb(t) order by id) from public.leaderboard_entries t) as results,
 (select jsonb_agg(to_jsonb(t) order by user_id) from public.cloud_saves t) as saves`);}
async function deniedAs(role,sql){
 await db.exec('savepoint permission_test');
 try{await db.exec('set local role '+role);await assert.rejects(db.query(sql),/permission denied/i);}
 finally{await db.exec('rollback to savepoint permission_test; release savepoint permission_test');}
}
try{
 await db.exec(`
 create role anon nologin; create role authenticated nologin; create role service_role nologin;
 create schema auth; create schema app_private;
 revoke all on schema app_private from public,anon,authenticated;
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 create table public.profiles(id uuid primary key,public_id uuid not null unique,username text,display_name text,avatar_url text);
 create table public.game_runs(id uuid primary key,user_id uuid not null references public.profiles(id),mode text not null,rules_version text not null,status text not null,created_at timestamptz not null,updated_at timestamptz not null default now());
 create table public.leaderboard_entries(id bigint generated by default as identity primary key,run_id uuid not null unique references public.game_runs(id),user_id uuid not null references public.profiles(id),mode text not null,points numeric(12,2) not null,wins smallint not null,losses smallint not null,team_ovr numeric(6,2) not null,rules_version text not null,result_digest text not null unique,roster jsonb not null default '{}',transcript jsonb not null default '[]',created_at timestamptz not null);
 create table public.cloud_saves(user_id uuid primary key references public.profiles(id),revision bigint not null,schema_version integer not null,payload jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
 alter table public.profiles enable row level security;
 alter table public.game_runs enable row level security;
 alter table public.leaderboard_entries enable row level security;
 alter table public.cloud_saves enable row level security;
 revoke all on public.profiles,public.game_runs,public.leaderboard_entries,public.cloud_saves from public,anon,authenticated;
 `);
 for(const [name,user]of Object.entries(users))await profile(user,'user_'+name);
 await db.query('insert into public.cloud_saves(user_id,revision,schema_version,payload) values($1,37,1,$2)',[users.a,{credits:1250,collection:{288:1,1293:2},packs:{gold:3},trophies:['perfect-draft','old-season'],ownedEffects:['lebron-heavy-is-the-head'],savedTeams:[{name:'82-0',roster:{C:1293}}],settings:{sound:false}}]);
 await db.query('insert into public.cloud_saves(user_id,revision,schema_version,payload) values($1,8,1,$2)',[users.b,{credits:400,collection:{3:1},packs:{silver:2},trophies:['collector'],ownedEffects:['verified-mythic']}]);
 const oldRun=await result({user:users.old,runAt:"now()-interval '30 days'",points:1102.95});
 const oldA=await result({user:users.a,runAt:"now()-interval '30 days'",points:1101});
 await result({user:users.a,mode:'one_v_one',runAt:"now()-interval '30 days'",points:100,wins:1});
 await result({user:users.b,mode:'one_v_one',runAt:'now()',points:90,wins:1});
 await db.exec(previous);
 await db.exec('revoke all on function public.get_leaderboard(text,text,integer),public.get_beta_season_status() from public; grant execute on function public.get_leaderboard(text,text,integer),public.get_beta_season_status() to anon,authenticated;');
 assert.equal((await leaderboard()).length,2,'Baseline must contain the old season leaders');
 const oldDuels=await leaderboard('one_v_one'),before=await tableSnapshot();
 const beforeApply=Date.now();await db.exec(migration);const afterApply=Date.now();
 assert.deepEqual(await tableSnapshot(),before,'Migration must preserve every historical result, run, cloud-save field, reward and revision');
 const season=await one('select * from app_private.classic_draft_seasons');
 assert.equal(season.season_id,'beta-20261010');assert.equal(season.name,'Beta season');assert.equal(season.singleton,true);
 assert(+season.starts_at>=beforeApply-1000&&+season.starts_at<=afterApply+1000,'Cutoff must be captured at migration application');
 for(const period of ['all_time','daily','weekly'])assert.deepEqual(await leaderboard('draft',period),[],'Fresh season must begin with an empty Classic leaderboard in '+period);
 assert.equal((await status()).eligible_players,0);assert.equal((await status()).season_id,'beta-20261010');
 assert.deepEqual(await leaderboard('one_v_one'),oldDuels,'Duel standings must not be reset');

 // Hold now() fixed while exercising calendar edges and exact cutoff equality.
 await db.exec('begin');
 await db.exec("update app_private.classic_draft_seasons set starts_at=date_trunc('week',now(),'UTC')-interval '1 week'");
 const cutoff="(select starts_at from app_private.classic_draft_seasons where singleton)";
 const modern=await result({user:users.a,points:1095}),history=await result({user:users.a,rules:'atu-history-draft-v12',points:1098});
 await result({user:users.b,points:1098});await result({user:users.b,rules:'atu-history-draft-v12',points:1090});
 await result({user:users.c,points:1100,runAt:cutoff,entryAt:cutoff});
 const board=await leaderboard();assert.deepEqual(board.map(r=>Number(r.rank)),[1,1,3],'Tied total points share a rank and leave the normal rank gap');
 assert.deepEqual(board.map(r=>Number(r.games)),[2,2,1]);assert.equal(Number(board[0].points),2098);assert.equal(Number(board[0].best_team_ovr),98);
 assert.equal((await status()).eligible_players,3,'Count all newly qualified players, including the exact cutoff boundary');
 assert.equal(Number(board[0].wins),164);assert.equal(Number(board[0].losses),0);

 // Pending old runs and edited old entries stay out, even if their first save
 // or most recent edit is after reset. Both timestamps and ownership matter.
 await result({user:users.pending,runAt:`${cutoff}-interval '1 microsecond'`,entryAt:'now()'});
 await result({user:users.pending,runAt:'now()',entryAt:`${cutoff}-interval '1 microsecond'`});
 await db.query('update public.leaderboard_entries set points=1119,created_at=now() where run_id=$1',[oldRun]);
 await db.query('update public.game_runs set updated_at=now() where id=$1',[oldRun]);
 await result({user:users.pending,runUser:users.a});
 await result({user:users.pending,runMode:'pack'});
 await result({user:users.pending,wins:81,losses:1});
 await result({user:users.pending,points:1059});await result({user:users.pending,points:1121});
 assert.deepEqual(await leaderboard(),board,'Stale, mismatched or non-perfect rows must not leak into the new season');
 assert.equal((await viewer(users.pending)).viewer,null);assert.equal((await viewer(users.old)).viewer,null);
 assert.equal((await one('select count(*)::int as n from public.leaderboard_entries where run_id=$1',[oldA])).n,1,'Old saves remain stored');

 // An upsert/revision remains one run; the unique run key still rejects a
 // second result row. The best team bonus, not a sum of bonuses, breaks ties.
 await db.query('update public.leaderboard_entries set points=1097,transcript=$2 where run_id=$1',[modern,[{type:'revision'}]]);
 assert.equal(Number((await leaderboard())[0].games),2);assert.equal(Number((await leaderboard())[0].points),2098);
 await db.exec('savepoint duplicate_run');
 await assert.rejects(db.query('insert into public.leaderboard_entries(run_id,user_id,mode,points,wins,losses,team_ovr,rules_version,result_digest,created_at) select run_id,user_id,mode,points,wins,losses,team_ovr,rules_version,$2,now() from public.leaderboard_entries where run_id=$1',[history,'different-digest']),/duplicate key/i);
 await db.exec('rollback to savepoint duplicate_run; release savepoint duplicate_run');

 // UTC daily and weekly periods intersect the season. An entry at each
 // boundary is included; one microsecond earlier is excluded from that period.
 await db.exec('savepoint calendar_edges');
 const week="date_trunc('week',now(),'UTC')",day="date_trunc('day',now(),'UTC')";
 await result({user:users.period,runAt:`${week}-interval '1 microsecond'`,points:1080});
 await result({user:users.period,runAt:week,points:1080});
 await result({user:users.period,runAt:`${day}-interval '1 microsecond'`,points:1080});
 await result({user:users.period,runAt:day,points:1080});
 const periodId=id(10007),daily=(await leaderboard('draft','daily')).find(r=>r.profile_id===periodId),weekly=(await leaderboard('draft','weekly')).find(r=>r.profile_id===periodId);
 const monday=(await one(`select (${day}=${week}) as same`)).same;
 assert.equal(Number(daily.games),monday?2:1);assert.equal(Number(weekly.games),monday?2:3);
 assert.equal(Number((await leaderboard()).find(r=>r.profile_id===periodId).games),4);
 await db.exec('rollback to savepoint calendar_edges; release savepoint calendar_edges');

 // Public population is complete even beyond the bounded leaderboard list.
 await db.exec('savepoint population');
 for(let i=0;i<102;i++){const user=id(100+i);await profile(user,'extra_'+i);await result({user,points:1080});}
 await result({user:users.newcomer,points:1060});
 assert.equal((await leaderboard('draft','all_time',1000)).length,100);assert.equal((await leaderboard('draft','all_time',0)).length,1);
 const mine=await viewer(users.newcomer);assert.equal(mine.eligible_players,106);assert.equal(mine.viewer.rank,106);assert.equal(mine.viewer.games,1);
 await db.exec('set local role authenticated');
 const theirs=await viewer(users.a);assert.equal(theirs.viewer.games,2);assert.equal(theirs.viewer.rank,1);
 const other=await viewer(users.c);assert.equal(other.viewer.games,1);assert.equal(other.viewer.rank,3,'Caller-specific status must change with auth.uid(), not return the prior caller');
 await db.exec('reset role; set local role anon');
 const publicStatus=await viewer(null);assert.equal(publicStatus.eligible_players,106);assert.equal(publicStatus.viewer,null);
 assert.equal((await leaderboard('draft','all_time',1000)).length,100,'Anonymous readers can see bounded public standings');
 await db.exec('reset role; rollback to savepoint population; release savepoint population');

 // No public/client table access or mutation is added. Only existing read RPCs
 // are callable, retaining SECURITY DEFINER, stable semantics and empty path.
 const security=await one(`select c.relrowsecurity as rls,
  has_schema_privilege('anon','app_private','USAGE') as anon_schema,
  has_schema_privilege('authenticated','app_private','USAGE') as authenticated_schema,
  has_table_privilege('anon','app_private.classic_draft_seasons','SELECT,INSERT,UPDATE,DELETE') as anon_table,
  has_table_privilege('authenticated','app_private.classic_draft_seasons','SELECT,INSERT,UPDATE,DELETE') as authenticated_table
 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='app_private' and c.relname='classic_draft_seasons'`);
 assert.deepEqual(security,{rls:true,anon_schema:false,authenticated_schema:false,anon_table:false,authenticated_table:false});
 const funcs=await rows(`select p.proname,p.prosecdef,p.provolatile,p.proconfig,
  has_function_privilege('anon',p.oid,'EXECUTE') as anon_execute,
  has_function_privilege('authenticated',p.oid,'EXECUTE') as authenticated_execute,
  exists(select 1 from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE') as public_execute
 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('get_leaderboard','get_beta_season_status') order by p.proname`);
 assert.equal(funcs.length,2);for(const f of funcs){assert.equal(f.prosecdef,true);assert.equal(f.provolatile,'s');assert.deepEqual(f.proconfig,['search_path=""']);assert.equal(f.anon_execute,true);assert.equal(f.authenticated_execute,true);assert.equal(f.public_execute,false);}
 for(const role of ['anon','authenticated']){
  await deniedAs(role,'select * from app_private.classic_draft_seasons');
  await deniedAs(role,"update app_private.classic_draft_seasons set starts_at='2000-01-01'");
  await deniedAs(role,'select * from public.cloud_saves');
 }
 await db.exec('savepoint singleton');
 await assert.rejects(db.query("insert into app_private.classic_draft_seasons values(false,'rogue','Rogue',now())"),/check constraint/i);
 await db.exec('rollback to savepoint singleton; release savepoint singleton');
 assert.deepEqual((await tableSnapshot()).saves,before.saves,'All credits, rewards, packs, cosmetics, saved teams and cloud revisions remain unchanged');
 assert.deepEqual(await leaderboard('one_v_one'),oldDuels,'Duel all-time standings remain unchanged after every Classic scenario');
 await db.exec('rollback');
 console.log('Beta season SQL passed in disposable PostgreSQL: old/late/revised runs excluded; Modern/History included; unique runs, tied ranks, cutoff and UTC calendar edges; complete public population and isolated caller progress; preserved saves/rewards/duels; private RLS table and unchanged read-only RPC access');
}finally{await db.close();}
