const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const context=vm.createContext({console,sGet:()=>null,sSet(){},awardCredits(){}});
const run=s=>vm.runInContext(s,context);
run(source.match(/<script>\s*\/\/<LOGIC>([\s\S]*?)\/\/<\/LOGIC>/)[1]);
run(source.slice(source.indexOf('const EFX_KEY='),source.indexOf('/* ---- overlay painters:')));
assert(run('EFFECTS.filter(e=>e.t==="Mythic").every(e=>e.k==="skin")'));
assert.equal(run('Object.values(EFX_ODDS).reduce((a,b)=>a+b,0)'),100);
assert.equal(run('EFX_BY_ID["a-blood"].t'),'Rare');
assert.equal(run('EFX_BY_ID["f-rune"].t'),'Uncommon');
assert.equal(run('EFX_BY_ID["f-notch"].t'),'Common');
run('globalThis.lebrons=DB.filter(p=>p&&p.name==="LeBron James");globalThis.other=DB.find(p=>p&&p.name!=="LeBron James"&&efxEligible(p));EFX.sincePity=44;globalThis.pull=openRaftersPack();');
assert.equal(context.pull.tier,'Mythic');assert.equal(context.pull.card.name,'LeBron James');
assert.equal(run('EFX.sincePity'),0);
assert(run('lebrons.every(p=>ownsEfx(p.id,pull.efx.id))'));
assert.equal(run('ownsEfx(other.id,pull.efx.id)'),false);
assert.equal(run('grantEfx(lebrons[1].id,pull.efx.id)'),true,'Other team counts as same skin duplicate');
run('equipEfx(lebrons[1].id,pull.efx.id)');
assert.equal(run('skinFor(lebrons[1]).slug'),'skins/lebron-heavy-is-the-head-20261003');
run(source.slice(source.indexOf('const CARD_ART_BASE='),source.indexOf('/* Dev helper: run artStatus()')));
const skinAsset='cards/skins/lebron-heavy-is-the-head-20261003.png';
assert.equal(run('cardArtURL(lebrons[1])'),skinAsset,'Equipped collection art uses the replacement PNG');
assert.deepEqual(Array.from(run('cardArtVariants(lebrons[1])')),[skinAsset],'Card art uses the same replacement PNG');
assert.equal(fs.readFileSync(require('node:path').join(__dirname,'..',skinAsset)).subarray(0,8).toString('hex'),'89504e470d0a1a0a');
const shareRequests=[];
context.Image=class{set src(value){shareRequests.push(value);this.onload();}};
run(source.slice(source.indexOf('const IMG_ART='),source.indexOf('function drawRosterCanvas(')));
run('preloadRosterArt({PG:lebrons[1].id})');
assert.deepEqual(shareRequests,[skinAsset],'Roster share exports preload the replacement PNG');
assert.equal(run('skinFor(lebrons[0])'),null,'Equipping is per team card');
run('equipEfx(other.id,pull.efx.id)');assert.equal(run('skinFor(other)'),null);
run('globalThis.saved=JSON.stringify(EFX);EFX=JSON.parse(saved)');
assert(run('lebrons.every(p=>ownsEfx(p.id,pull.efx.id))'),'Shared unlock survives save/reload');
assert.equal(run('skinFor(lebrons[1]).id'),'skin-lebron-king');
run('equipEfx(lebrons[1].id,pull.efx.id)');assert.equal(run('skinFor(lebrons[1])'),null);
for(let i=0;i<100;i++)assert.equal(run('openRaftersPack("Mythic").card.name'),'LeBron James');
console.log('Rafters rarity, guaranteed skin, shared unlock, duplicates, equip and persistence passed');
