begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_format check (
    username is null or username ~ '^[A-Za-z0-9_]{3,20}$'
  ),
  constraint profiles_display_name_length check (
    display_name is null or char_length(display_name) between 1 and 40
  )
);

create unique index if not exists profiles_username_lower_unique
  on public.profiles (lower(username))
  where username is not null;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    nullif(coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'), ''),
    nullif(coalesce(new.raw_user_meta_data ->> 'avatar_url', new.raw_user_meta_data ->> 'picture'), '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create table if not exists public.cloud_saves (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  schema_version integer not null default 1 check (schema_version > 0),
  payload jsonb not null default '{}'::jsonb,
  client_updated_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint cloud_saves_payload_object check (jsonb_typeof(payload) = 'object')
);

drop trigger if exists cloud_saves_set_updated_at on public.cloud_saves;
create trigger cloud_saves_set_updated_at
before update on public.cloud_saves
for each row execute function public.set_updated_at();

create table if not exists public.async_challenges (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  created_by uuid not null references public.profiles(id) on delete cascade,
  opponent_id uuid references public.profiles(id) on delete set null,
  winner_id uuid references public.profiles(id) on delete set null,
  status text not null default 'open'
    check (status in ('open', 'accepted', 'completed', 'expired', 'cancelled')),
  rules_version text not null,
  draft_seed text not null,
  expires_at timestamptz not null default (now() + interval '7 days'),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint async_challenges_distinct_players check (
    opponent_id is null or opponent_id <> created_by
  ),
  constraint async_challenges_winner_is_player check (
    winner_id is null or winner_id = created_by or winner_id = opponent_id
  )
);

create index if not exists async_challenges_created_by_idx
  on public.async_challenges (created_by, created_at desc);
create index if not exists async_challenges_opponent_idx
  on public.async_challenges (opponent_id, created_at desc)
  where opponent_id is not null;
create index if not exists async_challenges_status_expiry_idx
  on public.async_challenges (status, expires_at);

drop trigger if exists async_challenges_set_updated_at on public.async_challenges;
create trigger async_challenges_set_updated_at
before update on public.async_challenges
for each row execute function public.set_updated_at();

create table if not exists public.challenge_entries (
  challenge_id uuid not null references public.async_challenges(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  side smallint not null check (side in (1, 2)),
  roster jsonb not null,
  score numeric(12,2) not null check (score >= 0),
  team_ovr numeric(6,2) not null check (team_ovr between 0 and 200),
  projected_wins smallint not null check (projected_wins between 0 and 82),
  submitted_at timestamptz not null default now(),
  primary key (challenge_id, user_id),
  unique (challenge_id, side),
  constraint challenge_entries_roster_object check (jsonb_typeof(roster) = 'object')
);

create table if not exists public.leaderboard_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  mode text not null check (mode in ('draft', 'pack', 'one_v_one')),
  points numeric(12,2) not null check (points >= 0),
  wins smallint not null default 0 check (wins between 0 and 82),
  losses smallint not null default 0 check (losses between 0 and 82),
  team_ovr numeric(6,2) check (team_ovr between 0 and 200),
  roster jsonb,
  challenge_id uuid references public.async_challenges(id) on delete set null,
  run_hash text not null unique,
  rules_version text not null,
  created_at timestamptz not null default now(),
  constraint leaderboard_roster_object check (
    roster is null or jsonb_typeof(roster) = 'object'
  )
);

create index if not exists leaderboard_mode_created_points_idx
  on public.leaderboard_entries (mode, created_at desc, points desc);
create index if not exists leaderboard_user_mode_idx
  on public.leaderboard_entries (user_id, mode, created_at desc);

alter table public.profiles enable row level security;
alter table public.cloud_saves enable row level security;
alter table public.async_challenges enable row level security;
alter table public.challenge_entries enable row level security;
alter table public.leaderboard_entries enable row level security;

drop policy if exists "Profiles are publicly readable" on public.profiles;
create policy "Profiles are publicly readable"
on public.profiles for select
to anon, authenticated
using (true);

drop policy if exists "Users update their own profile" on public.profiles;
create policy "Users update their own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "Users read their own cloud save" on public.cloud_saves;
create policy "Users read their own cloud save"
on public.cloud_saves for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users create their own cloud save" on public.cloud_saves;
create policy "Users create their own cloud save"
on public.cloud_saves for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users update their own cloud save" on public.cloud_saves;
create policy "Users update their own cloud save"
on public.cloud_saves for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Challenge players read their match" on public.async_challenges;
create policy "Challenge players read their match"
on public.async_challenges for select
to authenticated
using (
  (select auth.uid()) = created_by
  or (select auth.uid()) = opponent_id
);

drop policy if exists "Challenge players read entries" on public.challenge_entries;
create policy "Challenge players read entries"
on public.challenge_entries for select
to authenticated
using (
  exists (
    select 1
    from public.async_challenges c
    where c.id = challenge_entries.challenge_id
      and ((select auth.uid()) = c.created_by or (select auth.uid()) = c.opponent_id)
  )
);

drop policy if exists "Verified leaderboard is publicly readable" on public.leaderboard_entries;
create policy "Verified leaderboard is publicly readable"
on public.leaderboard_entries for select
to anon, authenticated
using (true);

revoke insert, update, delete on public.async_challenges from anon, authenticated;
revoke insert, update, delete on public.challenge_entries from anon, authenticated;
revoke insert, update, delete on public.leaderboard_entries from anon, authenticated;

grant select on public.profiles to anon, authenticated;
grant select, insert, update on public.cloud_saves to authenticated;
grant select on public.async_challenges to authenticated;
grant select on public.challenge_entries to authenticated;
grant select on public.leaderboard_entries to anon, authenticated;

create or replace function public.set_username(p_username text)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_username text := trim(p_username);
  updated_profile public.profiles;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if clean_username !~ '^[A-Za-z0-9_]{3,20}$' then
    raise exception 'Username must be 3-20 characters using letters, numbers or underscores';
  end if;

  update public.profiles
  set username = clean_username
  where id = auth.uid()
  returning * into updated_profile;

  if updated_profile.id is null then
    raise exception 'Profile not found';
  end if;

  return updated_profile;
exception
  when unique_violation then
    raise exception 'Username is already taken';
end;
$$;

create or replace function public.create_async_challenge(p_rules_version text)
returns table (challenge_id uuid, challenge_code text, draft_seed text, expires_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_challenge public.async_challenges;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(p_rules_version), '') is null then
    raise exception 'Rules version is required';
  end if;

  insert into public.async_challenges (
    code,
    created_by,
    rules_version,
    draft_seed
  )
  values (
    upper(substr(encode(gen_random_bytes(8), 'hex'), 1, 12)),
    auth.uid(),
    trim(p_rules_version),
    encode(gen_random_bytes(16), 'hex')
  )
  returning * into new_challenge;

  return query
  select new_challenge.id, new_challenge.code, new_challenge.draft_seed, new_challenge.expires_at;
end;
$$;

create or replace function public.get_async_challenge(p_code text)
returns table (
  challenge_id uuid,
  challenge_code text,
  status text,
  creator_username text,
  rules_version text,
  draft_seed text,
  has_opponent boolean,
  expires_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    c.id,
    c.code,
    case when c.expires_at <= now() and c.status in ('open', 'accepted')
      then 'expired' else c.status end,
    coalesce(p.username, p.display_name, 'Player'),
    c.rules_version,
    c.draft_seed,
    c.opponent_id is not null,
    c.expires_at
  from public.async_challenges c
  join public.profiles p on p.id = c.created_by
  where c.code = upper(trim(p_code))
    and c.status <> 'cancelled'
  limit 1;
$$;

create or replace function public.accept_async_challenge(p_code text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.async_challenges;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into target
  from public.async_challenges
  where code = upper(trim(p_code))
  for update;

  if target.id is null then
    raise exception 'Challenge not found';
  end if;
  if target.expires_at <= now() then
    update public.async_challenges set status = 'expired' where id = target.id;
    raise exception 'Challenge has expired';
  end if;
  if target.created_by = auth.uid() then
    raise exception 'You cannot accept your own challenge';
  end if;
  if target.status <> 'open' or target.opponent_id is not null then
    raise exception 'Challenge is no longer available';
  end if;

  update public.async_challenges
  set opponent_id = auth.uid(), status = 'accepted'
  where id = target.id;

  return target.id;
end;
$$;

create or replace function public.get_leaderboard(
  p_mode text,
  p_period text default 'all_time',
  p_limit integer default 50
)
returns table (
  rank bigint,
  user_id uuid,
  username text,
  avatar_url text,
  games bigint,
  points numeric,
  wins bigint,
  losses bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with filtered as (
    select l.*
    from public.leaderboard_entries l
    where l.mode = p_mode
      and p_mode in ('draft', 'pack', 'one_v_one')
      and l.created_at >= case p_period
        when 'daily' then date_trunc('day', now())
        when 'weekly' then date_trunc('week', now())
        else '-infinity'::timestamptz
      end
  ),
  totals as (
    select
      f.user_id,
      count(*) as games,
      sum(f.points) as points,
      sum(f.wins)::bigint as wins,
      sum(f.losses)::bigint as losses
    from filtered f
    group by f.user_id
  ),
  ranked as (
    select
      row_number() over (order by t.points desc, t.wins desc, t.games asc, t.user_id) as rank,
      t.*
    from totals t
  )
  select
    r.rank,
    r.user_id,
    coalesce(p.username, p.display_name, 'Player') as username,
    p.avatar_url,
    r.games,
    r.points,
    r.wins,
    r.losses
  from ranked r
  join public.profiles p on p.id = r.user_id
  order by r.rank
  limit greatest(1, least(coalesce(p_limit, 50), 100));
$$;

revoke all on function public.set_username(text) from public;
revoke all on function public.create_async_challenge(text) from public;
revoke all on function public.get_async_challenge(text) from public;
revoke all on function public.accept_async_challenge(text) from public;
revoke all on function public.get_leaderboard(text, text, integer) from public;

grant execute on function public.set_username(text) to authenticated;
grant execute on function public.create_async_challenge(text) to authenticated;
grant execute on function public.get_async_challenge(text) to anon, authenticated;
grant execute on function public.accept_async_challenge(text) to authenticated;
grant execute on function public.get_leaderboard(text, text, integer) to anon, authenticated;

commit;
